[package]
name = "gcodekit_device_adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time"] }
async-trait = "0.1"
gcodekit_utils = { path = "../utils" }

[features]
async = []
