[package]
name = "gcodekit_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
gcodekit_device_adapters = { path = "../device-adapters" }
