name: Run ignored harnesses

on:
  workflow_dispatch:

jobs:
  harnesses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain-action@v1
        with:
          toolchain: stable
      - name: Build and run ignored tests (core)
        run: |
          cargo test --manifest-path crates/core/Cargo.toml -- --ignored --nocapture
